### ISSUE TITLE
# 切换到 前端 项目目录，根本没有那个目录

### ISSUE THREAD

**Issue by LifeActor** [xiaoliu978/Xin-Admin#4]
# 切换到 前端 项目目录
cd ./web/admin

web目录是存在的，admin目录压根不存在哇，无法进行这一步

另外 .env文件的换行符在linux环境下  vi 和 vim 都无法正确显示换行

**Comment by xinova** [comment]
Hello,Thank you for submitting the issues.
由于项目变动，将 web/admin 目录 移动至 /web 目录，你可以加入官方QQ群来了解相关信息
