### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by LifeActor** [xiaoliu978/Xin-Admin#5]
pnpm run dev
执行后，内存耗尽，
(⊙o⊙)…
一方面机器4H8G，可能真的已经老了，无可奈何，公司给配的
一方面，看能否有优化空间？

**Comment by xinova** [comment]
Hello,Thank you for submitting the issues.
对于前端项目，执行 pnpm run dev 一般情况下用于开发环境中使用，生产环境中使用npm server会占用系统大量资源，且损耗系统性能，你可以参考文档部署章节，将前端文件打包为静态资源之后再部署到服务器中
